name: Move to test
on:
  issues:
    types: [labeled]
    
jobs:
  move_cards:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: ${{ secrets.PAT }}
        project-url: https://github.com/LauraDaflon96/workshop-github-actions/projects/1
        column-name: "Awaiting test"
        label-name: "awaiting-test"
        columns-to-ignore: "Awaiting test, Resolved"
