name: Move to Test Column
on:
  issues:
    types: [labeled]

jobs:
  move_cards:
    runs-on: ubuntu-latest
    steps:
      - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
        with:
          action-token: "${{ secrets.MY_TOKEN }}"
          project-url: "${{ secrets.CURRENT_PROJECT_URL }}"
          column-name: "Awaiting test"
          label-name: "awaiting-test"
          columns-to-ignore: "Awaiting Test, Resolved"
